services:
  database:
    profiles: [dev, test, ci]
    image: mariadb:10.11
    ports:
      - ${DATABASE_PORT:-3307}:3306
    env_file:
      - .env
      - .env.local
    volumes:
      - ../cypress/data:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d/99-migrations
    hostname: crm-database
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 20s
      retries: 10

  mailserver:
    profiles: [dev, test]
    image: axllent/mailpit:latest
    ports:
      - ${MAILSERVER_PORT:-1026}:1025
      - ${MAILSERVER_GUI_PORT:-8026}:8025
    hostname: crm-mailserver

  webserver-dev:
    profiles: [dev]
    build:
      context: .
      dockerfile: Dockerfile.churchcrm-apache-php8
      target: dev
    image: churchcrm/crm:php8-debian-dev
    ports:
      - ${WEBSERVER_PORT:-8080}:80
    volumes:
      - ../src:/var/www/html
      - ..:/home/ChurchCRM
      - ../cypress/data/images/people:/var/www/html/Images/Person
      - ../cypress/data/images/family:/var/www/html/Images/Family
    hostname: crm-webserver
    env_file:
      - .env
      - .env.local
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      database:
        condition: service_healthy

  webserver-test:
    profiles: [test, ci]
    build:
      context: .
      dockerfile: Dockerfile.churchcrm-apache-php8
      target: test
    image: churchcrm/crm:php8-debian
    ports:
      - ${WEBSERVER_PORT:-80}:80
    volumes:
      - ../src:/var/www/html
      - ..:/home/ChurchCRM
      - ../cypress/data/images/people:/var/www/html/Images/Person
      - ../cypress/data/images/family:/var/www/html/Images/Family
    hostname: crm-webserver
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy

  adminer:
    profiles: [dev]
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=database
    ports:
      - ${ADMINER_PORT:-8089}:8080
    hostname: crm-adminer

volumes:
  mariadb_data:
    driver: local

